server:
  port:8088
spring:
  datasource:
    msdatasource:
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      password: yuxie1998
      username: root
      driver-class-name: com.mysql.jdbc.Driver
